[package]
name = "charcoal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.6.0"
solang-parser = "0.3.3"
structopt = { version = "0.3", default-features = false }
